Eshop.MVC/Controllers/ShoppingCartController.cs
using Eshop.CORE.Contracts;
using Eshop.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Eshop.IFR.Log;
using Eshop.IFR.Paypal;
using PayPal.Api;
using Eshop.CORE;
using Eshop.IFR.Email;

namespace Eshop.MVC.Controllers
{
    public class ShoppingCartController : Controller
    {

        //Manager de CartItem
        private ICartItemManager _cartItemManager = null;
        private ILogEvent _logManager = null;
        private IPaypalManager _paypalManager = null;
        private  IProductManager _productManager = null;
        private IOrderManager _orderManager = null;
        private IMyUserManager _userManager = null;
        private IEmailManager _emailManager = null;

        public int totalValue;
        /// <summary>
        /// Constructor de cartItemController
        /// </summary>
        /// <param name="productManager"></param>
        public ShoppingCartController(ICartItemManager cartItemManager)
        {
            this._cartItemManager = cartItemManager;
        }

        public ShoppingCartController(IMyUserManager myUserManager, ICartItemManager cartItemManager, IPaypalManager paypalManager, ILogEvent log, IProductManager productManager, IOrderManager orderManager , IEmailManager emailManager)
        {
            this._cartItemManager = cartItemManager;
            this._logManager = log;
            this._paypalManager = paypalManager;
            this._productManager = productManager;
            this._orderManager = orderManager;
            this._userManager = myUserManager;
            this._emailManager = emailManager;
        }

        public List<CartItemModel> UserCartItems { get; set; }


        // GET: ShoppingCart
        public ActionResult Index()
        {
            UserCartItems = _cartItemManager.GetCartItemByUser(User.Identity.GetUserId()).Select(c => new CartItemModel
            {
                Id = c.Id,
                CartId = c.CartId,
                DateCreated = c.DateCreated,
                Product = c.Product,
                ProductId = c.ProductId,
                Quantity = c.Quantity,
                Imagen = c.Product.Imagenes.FirstOrDefault().urlImage

            }).ToList();


            return View(UserCartItems);
        }


        // GET: ShoppingCart/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ShoppingCart/Edit/5
        [HttpPost]
        public ActionResult Edit(String cartId, int quantity, int idProducto)
        {
            try
            {
                // recogemos el cartItem
                var cartItem = _cartItemManager.GetCartItemByUserAndProduct(cartId, idProducto).FirstOrDefault();
                //recogemos el producto para comprobar stock
                int stock = _productManager.GetById(idProducto).UnitsInStock;

                if (cartItem != null)
                {


                    //si  el nuevo stock es mayor que -1
                    if((stock - quantity) > -1)
                    {
                        //guardamos las propiedades que nos interesan

                        cartItem.Quantity = quantity;
                        _cartItemManager.Context.SaveChanges();
                    }
                    else
                    {
                        //Actualizamos el carrito con el maximo de stock disponible

                        cartItem.Quantity = stock;
                        _cartItemManager.Context.SaveChanges();

                    }

                }

                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                _logManager.WriteError(ex.Message, ex);
                return View();
            }
        }

        // GET: ShoppingCart/Delete/5
        public ActionResult Delete(int id, String prueba)
        {
            return View();
        }

        // POST: ShoppingCart/Delete/5
        [HttpPost]
        public ActionResult Delete(String cartId, int idProducto)
        {

            try
            {
                // recogemos el objeto de carrito de parametro
                var cartItem = _cartItemManager.GetCartItemByUserAndProduct(cartId, idProducto).FirstOrDefault();
                if (cartItem != null)
                {
                                        
                    //lo eliminamos mediante el manager
                    _cartItemManager.Remove(cartItem);
                    _cartItemManager.Context.SaveChanges();
                }


                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                _logManager.WriteError(ex.Message, ex);

                return View();
            }
        }


        //pago paypal

        private Payment payment;

        //creamos un pago de paypal usando su contexto



        private Payment CreatePayment(APIContext apiContext, string redirectUrl)
        {
            var listItems = new ItemList() { items = new List<Item>() };

            List<CartItemModel> cartItemsList = _cartItemManager.GetCartItemByUser(User.Identity.GetUserId()).Select(c => new CartItemModel
            {
                Id = c.Id,
                CartId = c.CartId,
                DateCreated = c.DateCreated,
                Product = c.Product,
                ProductId = c.ProductId,
                Quantity = c.Quantity,
                Imagen = c.Product.Imagenes.FirstOrDefault().urlImage

            }).ToList();


            foreach(var cartItem in cartItemsList)
            {
                listItems.items.Add(new Item()
                {

                    name = cartItem.Product.Name,
                    currency = "EUR",
                    price = cartItem.Product.Price.ToString(),
                    quantity = cartItem.Quantity.ToString(),
                    sku = "sku"

                });
            }

            var payer = new Payer() { payment_method = "paypal" };

            //configuracion de redirectURLS con el objeto

            var redirUrls = new RedirectUrls()
            {
                cancel_url = redirectUrl,
                return_url = redirectUrl
            };

            //creamos el objeto details
            var details = new Details()
            {
                tax = "0",
                shipping = "0",
                subtotal = cartItemsList.Sum(x=> x.Quantity * x.Product.Price).ToString() 

            };

            //creamos objeto amount

            var amount = new Amount()
            {
                currency = "EUR",
                total = (Convert.ToDouble(details.tax) + Convert.ToDouble(details.shipping) + Convert.ToDouble(details.subtotal)).ToString(), //tax+shipping+subtotal
                details = details
            };

            //creamos transaccion
            var transactionList = new List<Transaction>();
            transactionList.Add(new Transaction()
            {
                description = "Transacción de Eshop Miguel",
                invoice_number = (Convert.ToString(new Random().Next(100000))),
                amount = amount,
                item_list = listItems
            });

            payment = new Payment()
            {
                intent = "sale",
                payer = payer, 
                transactions = transactionList,
                redirect_urls = redirUrls
            };


            return payment.Create(apiContext);

        }

        //creamos execute payment method

        private Payment ExecutePayment(APIContext apiContext, string payerId, string paymentId)
        {
            var paymentExecution = new PaymentExecution()
            {
                payer_id = payerId
            };
            payment = new Payment()
            {
                id = paymentId
            };

            return payment.Execute(apiContext, paymentExecution);
        }

        //metodo para crear paymentwithpaypal

        public ActionResult PaymentWithPaypal()
        {
            //recogemos contexto con el manager

            APIContext apiContext = _paypalManager.GetAPIContext();

            try
            {

                string payerId = Request.Params["PayerID"];
                if (string.IsNullOrEmpty(payerId))
                {

                    //creamos un pago

                    string baseURI = Request.Url.Scheme + "://" + Request.Url.Authority + "/ShoppingCart/PaymentWithPaypal?";
                    var guid = Convert.ToString(new Random().Next(100000));
                    var createdPayment = CreatePayment(apiContext, baseURI + "guid=" + guid);


                    //obtenemos de vuelta los links de paypal de la respuesta

                    var links = createdPayment.links.GetEnumerator();
                    string paypalRedirectUrl = string.Empty;

                    while (links.MoveNext())
                    {
                        Links link = links.Current;

                        if (link.rel.ToLower().Trim().Equals("approval_url"))
                        {
                            paypalRedirectUrl = link.href;
                        }
                    }
                    Session.Add(guid, createdPayment.id);




                    return Redirect(paypalRedirectUrl);


                }
                else
                {
                    //esto se ejecutara cuando hayamos recibido todos los params del pago de la llamada anterior
                    var guid = Request.Params["guid"];
                    var executedPayment = ExecutePayment(apiContext, payerId, Session[guid] as string);

                    if(executedPayment.state.ToLower() != "approved")
                    {
                        return View("Failure");
                    }

                }

            }catch(Exception ex)
            {

Eshop.MVC/Views/ShoppingCart/Failure.cshtml
@{
    ViewBag.Title = "Failure";
}

<h2>Failure</h2>

Eshop.MVC/Views/ShoppingCart/Index.cshtml
@model IEnumerable<Eshop.MVC.Models.CartItemModel>

@{
    ViewBag.Title = "Index";
    var totalPriceOrder = 0;
}
<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<div class="container">
    <div class="row" style="margin-top:50px">
        <h2>Carrito</h2>
        <div class="col-sm-12 col-md-10 col-md-offset-1">
            <table class="table table-hover" style="margin-top:20px">
                <thead>
                    <tr>
                        <th>Producto</th>
                        <th>Cantidad</th>
                        <th class="text-center">Precio</th>
                        <th class="text-center">Total</th>
                        <th> </th>
                    </tr>
                </thead>
                <tbody>
                    @*FILA PRODUCTO*@

                    @*si no hay nada en el carrito*@
                    @if (!Model.Any())
                    {
                        <h4 style="color: red">El carrito esta vacío</h4>
                    }
                    else
                    {
                        foreach (var product in Model)
                        {
                            var price = product.Product.Price;
                            var totalPriceProduct = price * product.Quantity;
                            totalPriceOrder = Decimal.ToInt32(totalPriceOrder) + Decimal.ToInt32(totalPriceProduct);
                <tr id="@product.CartId">
                    <td class="col-sm-8 col-md-6">
                        <div class="media">
                            <a class="thumbnail pull-left" href="~/Product/Details/@product.ProductId"> <img class="media-object" src="@product.Imagen" style="width: 72px; height: 72px;"> </a>
                            <div class="media-body">
                                <h4 class="media-heading"><a href="~/Product/Details/@product.ProductId">@product.Product.Name</a></h4>
                                @*<h5 class="media-heading"> by <a href="#">@product.Id.ToString()</a></h5>*@
                                <span>Stock: </span><span class="text-success"><strong>@product.Product.UnitsInStock</strong></span>
                            </div>
                        </div>
                    </td>
                    <td class="col-sm-1 col-md-1" style="text-align: center">
                        <input type="text" class="form-control" id="quantityField_@product.Product.Id" value="@product.Quantity">
                    </td>
                    <td class="col-sm-1 col-md-1 text-center"><strong>@price €</strong></td>
                    <td class="col-sm-1 col-md-1 text-center"><strong>@totalPriceProduct €</strong></td>
                    <td class="col-sm-1 col-md-1">
                        <button type="button" class="btn btn-danger remove-cart-item" href="#" data-id="@product.CartId" data-id2="@product.Product.Id" >
                            <span class="glyphicon glyphicon-remove"></span> Quitar
                        </button>
                    </td>
                    <td class="col-sm-1 col-md-1">
                        <button type="button" class="btn btn-warning update-cart-item" href="#" data-id="@product.CartId"  data-quantity="5" data-id2="@product.Product.Id">
                            <span class="glyphicon glyphicon-refresh"></span> Actualizar
                        </button>
                    </td>
                </tr>



                        }

                    }


                    <tr>
                        <td>   </td>
                        <td>   </td>
                        <td>   </td>
                        <td><h5>Subtotal</h5></td>
                        <td class="text-right"><h5><strong>@totalPriceOrder €</strong></h5></td>
                    </tr>
                    <tr>
                        <td>   </td>
                        <td>   </td>
                        <td>   </td>
                        <td><h5>Coste envío estimado</h5></td>
                        <td class="text-right"><h5><strong>0 €</strong></h5></td>
                    </tr>
                    <tr>
                        <td>   </td>
                        <td>   </td>
                        <td>   </td>
                        <td><h3>Total</h3></td>
                        <td class="text-right"><h3><strong>@totalPriceOrder €</strong></h3></td>
                    </tr>
                    <tr>
                        <td>   </td>
                        <td>   </td>
                        <td>
                            <a href="/Shop" class="btn btn-default">
                                <span class="glyphicon glyphicon-shopping-cart"></span> Sigue comprando
                            </a>
                        </td>

                        <td>
                            @*<button type="button" class="btn btn-warning">
                                Actualizar Carrito <span class="glyphicon glyphicon-play"></span>
                            </button>
                            <br />*@
                            <a href="@Url.Action("PaymentWithPaypal", "ShoppingCart")" class="btn btn-success">
                                Checkout <span class="glyphicon glyphicon-play"></span>
                            </a>


                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>





@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Eshop.MVC/Views/ShoppingCart/Success.cshtml
@{
    ViewBag.Title = "Success";
}

<h2>Success</h2>