Eshop.MVC/Controllers/ShopController.cs
using Eshop.CORE;
using Eshop.CORE.Contracts;
using Eshop.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace Eshop.MVC.Controllers
{
    public class ShopController : Controller
    {


        IProductManager productManager = null;
        ICategoryManager categoryManager = null;


        private List<ProductModelCatalog> Products { get; set; }
        public List<CategoryModelCatalog> Categories { get; set; }

        /// <summary>
        /// Constructor vacio
        /// </summary>
        public ShopController(ICategoryManager categoryManager)
        {
            Categories = categoryManager.GetAllCategories().Select(p => new CategoryModelCatalog
            {
                Id = p.Id,
                Name = p.Name
            }).ToList();


        }

        public ShopController(IProductManager productManager, ICategoryManager categoryManager)
        {

            this.productManager = productManager;
            this.categoryManager = categoryManager;

            // Traemos las categorias de su clase enum
            //Categories = Enum.GetValues(typeof(Category)).Cast<Category>().ToList();
            //Categories = categoryManager.GetAllCategories().ToList();

            Categories = categoryManager.GetAllCategories().Select(p => new CategoryModelCatalog
            {
                Id = p.Id,
                Name = p.Name
            }).ToList();


            //recogemos listado de productos via manager
            Products = productManager.GetAll().Select(e => new ProductModelCatalog
            {
                Id = e.Id,
                Name = e.Name.ToString(),
                Description = e.Description.ToString(),
                UnitsInStock = e.UnitsInStock,
                Duration = e.Duration,
                Price = e.Price,
                Imagenes = e.Imagenes,
                YtURL = e.YtURL,
                Category = e.Category


            }).ToList();
        }

        // GET: Shop
        public ActionResult Index(int? category = null)
        {

            ShopModel model = new ShopModel
            {
                Categories = Categories,
                Products = Products.Where(p => category == null || p.Category.Id.Equals((int)category)).ToList()
            };



            return View(model);
        }



        // GET: Shop/Create
        public ActionResult Create()
        {
            return View();
        }



        /// <summary>
        /// metodo que añade al carrito
        /// </summary>
        /// <param name="productId"></param>
        /// <returns></returns>
        public ActionResult AddCartItem(int productId)
        {
            var count = AddProduct(productId);
            return Content(count.ToString());
        }


        private int AddProduct(int productId, int quantity = 1)
        {
            string userId = null;
            if (User.Identity.IsAuthenticated)
            {
                userId = User.Identity.GetUserId();
            }
            else
            {
                userId = Session.SessionID;
            }

            Dictionary<int, int> cart = Session["CartItem"] as Dictionary<int, int>;
            if (cart == null)
                cart = new Dictionary<int, int>();
            if (cart.ContainsKey(productId))
                cart[productId] = cart[productId] + quantity;
            else
                cart.Add(productId, 1);

            Session["CartItem"] = cart;

            return cart.Sum(e => e.Value);
        }
    }
}

Eshop.MVC/Areas/Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Eshop MiguelM", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">

                @if (Request.IsAuthenticated)
                {
                    if (User.IsInRole("Client"))
                    {
                        @Html.ActionLink("Tienda", "Index", "Shop", new { area = "" }, new { @class = "navbar-brand" })
                        @Html.ActionLink("Mis Pedidos", "Index", "Order", new { area = "Client" }, new { @class = "navbar-brand" })
                    }
                    if (User.IsInRole("Admin"))
                    {
                        <ul class="nav navbar-nav">
                            @Html.ActionLink("Tienda", "Index", "Shop", new { area = "" }, new { @class = "navbar-brand" })
                            @Html.ActionLink("Mis Pedidos", "Index", "Order", new { area = "Client" }, new { @class = "navbar-brand" })
                            @Html.ActionLink("Portal Administración", "Index", "Order", new { area = "Client" }, new { @class = "navbar-brand" })


                        </ul>
                    }
                }
                else
                {
                    @Html.ActionLink("Tienda", "Index", "Shop", new { area = "" }, new { @class = "navbar-brand" })

                }


                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Eshop Miguel MVC</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/cart")
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
            integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
            crossorigin="anonymous"></script>

    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {

            $('#orderClientList').DataTable();


        });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>